### ISSUE TITLE
MPS or even more general?

### ISSUE THREAD

**Issue by mfherbst** [mfherbst/ReducedBasis.jl#21]
Some functions that we have in mps.jl are not actually specific to MPS, but instead provide just a more general way of doing something than assuming the ability to access into dense memory for the operator (example is `extend` in src/mps.jl) if I'm not mistaken. In that case they should not be in the  src/mps.jl file but instead in the standard file (in this case rbasis.jl) and just not have any type annotation --- whereas the Matrix-based data structures would have an appropriate matrix annotation.

**Comment by pbrehmer** [comment]
Moved the MPS `extend` and `compress` methods to src/rbasis.jl and adjusted the type annotations. Now, src/mps.jl should only cover "truly" MPS-specific functions.
