### ISSUE TITLE
`extend` function interface

### ISSUE THREAD

**Issue by mfherbst** [mfherbst/ReducedBasis.jl#27]
The return value interface of the `extend` function differs between the `QRCompress` and `NoCompress` version. This should be unified (e.g. using a named tuple and/or dummy values).

**Comment by pbrehmer** [comment]
All `extend` methods now return the same `NamedTuple` up to additional, method-specific information.

**Comment by mfherbst** [comment]
Please don't close issues until the respective PR is merged into master.

**Comment by pbrehmer** [comment]
Didn't know, sorry. That does make more sense.
