### ISSUE TITLE
Add more quantities to `info` during greedy assembly

### ISSUE THREAD

**Issue by pbrehmer** [mfherbst/ReducedBasis.jl#38]
The reduced basis vectors that are computed on the offline grid in each greedy iteration should be also put into the `info` tuple. One possible advantage of this would be that, using the `InfoCollector`, we could collect the RB-vector grid for each iteration and then visualize the splitting of Voronoi cells in the parameter domain as the assembly progresses.

**Comment by pbrehmer** [comment]
In addition, we should also put any information (besides the values and vectors) that the solvers output into `info`.

**Comment by mfherbst** [comment]
> we should also put any information (besides the values and vectors) that the solvers output into info.

I agree on that point. The rest of the issue is void.
